stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  image: ruby:latest
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY